<div class="block widget">
        <div class="owl-carousel number-owl">
            <div class="item">
                <div class="col-12 img p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('img_4')
                        ->toHtml();
                    ?>
                </div>
                <div class="col-12 title p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('content_three_mini_child_1_1')
                        ->toHtml();
                    ?>
                </div>
                <div class="col-12 link p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('content_three_mini_child_1_2')
                        ->toHtml();
                    ?>
                </div>
            </div>
            <div class="item">
                <div class="col-12 img p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('img_5')
                        ->toHtml();
                    ?>
                </div>
                <div class="col-12 title p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('content_three_mini_child_2_1')
                        ->toHtml();
                    ?>
                </div>
                <div class="col-12 link p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('content_three_mini_child_2_2')
                        ->toHtml();
                    ?>
                </div>
            </div>
            <div class="item">
                <div class="col-12 img p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('img_7')
                        ->toHtml();
                    ?>
                </div>
                <div class="col-12 title p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('content_three_mini_child_3_1')
                        ->toHtml();
                    ?>
                </div>
                <div class="col-12 link p-0">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('content_three_mini_child_3_2')
                        ->toHtml();
                    ?>
                </div>
            </div>
        </div>
    </div>

<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owlcarousel'
    ], function($){
        $(document).ready(function() {
            $('.owl-carousel.number-owl ').owlCarousel({
                loop:false,
                margin: 10,
                items:3,
                responsive: {
                    300: {
                        items: 1.5
                    },
                    767: {
                        items: 3
                    }
                }
            });

        });
    });
</script>