<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */

// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New In');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist) :?>

    <div class="block widget block-new-products <?= /* @noEscape */ $mode ?>">
        <div class="block-title">
            <div class="title-new-in"><strong role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong></div>
            <div class="title-discover"><strong role="heading" aria-level="2">Discover</strong></div>

        </div>
        <div class="block-content ">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>  owl-carousel owl-theme">
<!--                <ol class="product-items --><?//= /* @noEscape */ $type ?><!-- ">-->

                    <?php  foreach ($items as $_item) :  ?>
<!--                        <li class="product-item">-->
                                <div class="item">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <p>925 Sikver Twist Earrings</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <p>925 Sikver Twist Earrings</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <p>925 Sikver Twist Earrings</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <p>925 Sikver Twist Earrings</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-photo">
                                        <?= $block->getImage($_item, $image)->toHtml() ?>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <p>925 Sikver Twist Earrings</p>
                                    </div>
                                </div>



<!--                        </li>-->
                    <?php  endforeach  ?>

<!--                </ol>-->
            </div>
        </div>
    </div>


<?php endif;?>

<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owlcarousel'
    ], function($){
        $(document).ready(function() {
            $('.owl-carousel.owl-theme ').owlCarousel({
                loop:true,
                margin: 10,
                nav:true,
                navText:["<i class='fas fa-angle-left'></i>","<i class='fas fa-angle-right'></i>"],
                items:4.5,
                responsive: {
                    300: {
                        items: 1.5
                    },
                    481: {
                        items: 2.5
                    },
                    590: {
                        items: 2.5
                    },
                    650: {
                        items: 3.5
                    },
                    767: {
                        items: 3.5
                    },
                    960: {
                        items: 4.5
                    },
                    1000: {
                        items: 4.5
                    }
                }
            });

        });
    });
</script>
